### ISSUE TITLE
turn list of graph algorithms into issues with progress tracking

### ISSUE THREAD

**Issue by jexp** [neo4j-contrib/neo4j-graph-algorithms#72]
create card for reach algorithm track progress in 

- [ ] implement baseline
- [ ] test baseline
- [ ] performance test baseline
- [ ] parallelization
- [ ] performance test parallelization
- [ ] different APIs / memory structures

* Implementation of the selected algorithms and exposed them as a Java API and Java Stored Procedure
   * PageRank
   * Label Propagation
   * Louvain
   * Betweenness Centrality
   * Closeness Centrality
   * Degree Centrality
   * Single Shortest Path
   * Strongly, Weakly connected components
   * Parallel BFS / DFS
* Evaluation
   * Performance Tests (different dataset sizes, regressions, level of concurrency)
   * Performance comparison with other implementations (Spark/Flink/Graphlytic) on same dataset and same level of concurrency
   * Review existing implementations for its functional correctness and performance:
      * A*
      * Dijkstra
      * Shortest Path

**Comment by jexp** [comment]
Added a few algorithms from an APOC issue
