### ISSUE TITLE
Algorithm: Label Propagation

### ISSUE THREAD

**Issue by mknblch** [neo4j-contrib/neo4j-graph-algorithms#95]
_Label Propagation_ is a clustering algorithm already implemented in current apoc-procedures. 

## Progress

- [ ] adapt apoc-procedure to algorithm api
- [ ] single threaded implementation
- [x] tests
- [ ] edge case tests
- [x] implement procedure
- [ ] simple benchmark 
- [ ] benchmark on bigger graphs
- [ ] parallelization
- [ ] evaluation
- [ ] documentation

## TODO

- adapt existing procedure to algorithm api

**Comment by jexp** [comment]
@knutwalker @maxdemarzi also had a label propagation, could you quickly check if that's better implemented? Please also check the others.
https://github.com/maxdemarzi/graph_processing#algorithms-implemented

**Comment by knutwalker** [comment]
Sure thing, will do!
