### ISSUE TITLE
Algorithm: Betweenness Centrality

### ISSUE THREAD

**Issue by mknblch** [neo4j-contrib/neo4j-graph-algorithms#98]
_Betweenness Centrality_ is a measure of centrality in a graph based on shortest paths. For every pair of vertices in a connected graph, there exists at least one shortest path between the vertices such that either the number of edges that the path passes through or the sum of the weights of the edges is minimized. The betweenness centrality for each vertex is the number of these shortest paths that pass through the vertex.

## Progress

- [ ] adapt apoc-procedure to algorithm-api
- [x] implement procedure
- [x] tests
- [ ] edge case tests
- [ ] simple benchmark 
- [ ] benchmark on bigger graphs
- [ ] parallelization
- [ ] evaluation
- [ ] documentation

## TODO

- adapt apoc-procedure to algorithm-api

**Comment by mknblch** [comment]
We have 3 different implementations so far

- a sequential BC algorithms as described by Brandes 
- out parallel adaptation if this algo
- a slightly changed brandes-algo which should be considered as experimental (must be tested on different kinds of graphs)

**Comment by mknblch** [comment]
@tomasonjo Do we already have documentation?

**Comment by tomasonjo** [comment]
I see only two version:

=== algo.betweenness

- implementation of brandes-bc algorithm and nodePartitioning extension
- http://www.algo.uni-konstanz.de/publications/b-fabc-01.pdf
- if `concurrency` parameter is set (and >1) ParallelBetweennessCentrality
is used
- ParallelBC spawns N(given by the concurrency param) concurrent threads
for calculation where each one
 calculates the BC for one node at a time

=== algo.betweenness.exp1

- brandes-like algorithm which uses successor sets instead of predecessor
sets
- The algorithm is based on Brandes definition but with some changes
 regarding the dependency-accumulation step.
- http://cass-mt.pnnl.gov/docs/pubs/georgiatechlbnlpnnlfastbc-mtaap2009.pdf

**Comment by JoKre17** [comment]
Is there the intention to make a weighted version of the betweenness centrality?

I guess I didn't really thought this through, but wouldn't it be possible e.g. for the normal BetweennessCentrality.java to replace the distances array with a float/double distances array and iterate over the relationships via the WeightedRelationshipIterator?

In most of the cases there won't be any or really small sigma values, I am not sure, wether this would be an issue, but I guess not.
